<?php
namespace App\Core\Framework\Classes;

class Strings{
	public const API_UNHANDLED_EXCEPTION = 'API_UNHANDLED_EXCEPTION';
	public const APP_NAME = 'APP_NAME';
	public const APP_DESCRIPTION = 'APP_DESCRIPTION';
	public const APP_DESCRIPTION_NO_NAME = 'APP_DESCRIPTION_NO_NAME';
	public const APP_INTERNAL_SERVER_ERROR_EXPLAIN = 'APP_INTERNAL_SERVER_ERROR_EXPLAIN';
	public const APP_LOGO_FILENAME = 'APP_LOGO_FILENAME';
	public const APP_PAGE_NOT_FOUND_EXPLAIN = 'APP_PAGE_NOT_FOUND_EXPLAIN';
	public const APP_PAGE_ON_BUILDING_EXPLAIN = 'APP_PAGE_ON_BUILDING_EXPLAIN';

	public const BUILDING_PAGE = "BUILDING_PAGE";

	public const CONTROLLER_NOT_FOUND = 'CONTROLLER_NOT_FOUND';

	public const DATABASE_OPERATION_SUCCESS = "DATABASE_OPERATION_SUCCESS";
	public const DATABASE_OPERATION_FAILED = "DATABASE_OPERATION_FAILED";

	public const DATABASE_SELECT_SUCCESS = "DATABASE_SELECT_SUCCESS";
	public const DATABASE_SELECT_FAILED = "DATABASE_SELECT_FAILED";

	public const DATABASE_INSERT_SUCCESS = "DATABASE_INSERT_SUCCESS";
	public const DATABASE_INSERT_FAILED = "DATABASE_INSERT_FAILED";

	public const DATABASE_UPDATE_SUCCESS = "DATABASE_UPDATE_SUCCESS";
	public const DATABASE_UPDATE_FAILED = "DATABASE_UPDATE_FAILED";

	public const DATABASE_DELETE_SUCCESS = "DATABASE_DELETE_SUCCESS";
	public const DATABASE_DELETE_FAILED = "DATABASE_DELETE_FAILED";

	public const EMPTY = "EMPTY";

	public const INCOMPLETE_POST = 'INCOMPLETE_POST';

	public const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';

	public const FORBIDDEN = 'FORBIDDEN';

	public const METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED';

	public const NOT_FOUND = "NOT_FOUND";

	public const NOT_LOGGED_IN = "NOT_LOGGED_IN";

	public const QUERY_ERROR = 'QUERY_ERROR';
	public const QUERY_UNSOLVED = 'QUERY_UNSOLVED';
	public const QUERY_NO_ROWS = 'QUERY_NO_ROWS';
	public const QUERY_SUCCESS = 'QUERY_SUCCESS';
	public const REQUEST_UNDEFINED = "REQUEST_UNDEFINED";

	public const REGEX_FAILED = "REGEX_FAILED";

	public const SUCCESSFUL_LOGIN = "SUCCESSFUL_LOGIN";

	public const UNKNOW_ACTION = 'UNKNOW_ACTION';

	public const UNSUCCESSFUL_LOGIN = "UNSUCCESSFUL_LOGIN";

	public const VIEW_NOT_FOUND = "VIEW_NOT_FOUND";
}